import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { ShoppingCart, BarChart3, Settings, ChevronRight } from 'lucide-react'
import { GroceryPage } from './GroceryPage'
import { ProgressPage } from './ProgressPage'
import { SettingsPage } from './SettingsPage'

type SubPage = 'menu' | 'grocery' | 'progress' | 'settings'

const CARD   = 'var(--bg-card)'
const RAISED = 'var(--bg-raised)'
const BORDER = 'var(--border)'
const VOLT   = 'var(--volt)'
const TXT2   = 'var(--text-secondary)'
const TXT3   = 'var(--text-muted)'

export function MorePage() {
  const { t } = useTranslation()
  const [subPage, setSubPage] = useState<SubPage>('menu')

  const BackBtn = () => (
    <button
      onClick={() => setSubPage('menu')}
      style={{ color: VOLT }}
      className="text-sm mb-3 flex items-center gap-1"
    >
      ← Back
    </button>
  )

  if (subPage === 'grocery')  return <div><BackBtn /><GroceryPage /></div>
  if (subPage === 'progress') return <div><BackBtn /><ProgressPage /></div>
  if (subPage === 'settings') return <div><BackBtn /><SettingsPage /></div>

  const items = [
    { id: 'grocery'  as SubPage, icon: ShoppingCart, label: t('grocery.title'),  desc: t('grocery.autoGenerated') },
    { id: 'progress' as SubPage, icon: BarChart3,    label: t('progress.title'), desc: 'Charts, streaks, benchmarks' },
    { id: 'settings' as SubPage, icon: Settings,     label: t('settings.title'), desc: 'Profile, targets, data' },
  ]

  return (
    <div className="space-y-3">
      <h1 className="text-xl font-bold text-white">{t('tabs.more')}</h1>
      {items.map(({ id, icon: Icon, label, desc }) => (
        <button
          key={id}
          onClick={() => setSubPage(id)}
          style={{ background: CARD, borderColor: BORDER }}
          className="w-full rounded-2xl p-4 border flex items-center gap-4 active:opacity-70 transition-opacity"
        >
          <div style={{ background: RAISED }} className="w-10 h-10 rounded-xl flex items-center justify-center">
            <Icon size={20} style={{ color: VOLT }} />
          </div>
          <div className="text-left flex-1">
            <p className="text-sm font-semibold text-white">{label}</p>
            <p style={{ color: TXT3 }} className="text-[10px]">{desc}</p>
          </div>
          <ChevronRight size={16} style={{ color: TXT2 }} />
        </button>
      ))}
    </div>
  )
}
